server:
  port: 80
spring:
  profiles:
    active: dev
  http:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mvc:
    favicon:
      enabled: false
management:
  security:
    enabled: false
  context-path: /admin
endpoints:
  shutdown:
    enabled: true